# Generated by Django 6.0.4 on 2026-04-13 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalAcademico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entidad', models.CharField(max_length=100)),
                ('cedula', models.CharField(blank=True, max_length=20, null=True)),
                ('nombre_apellido', models.CharField(max_length=200)),
                ('responsabilidad', models.CharField(default='GESTION ACADEMICA', max_length=100)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('correo', models.EmailField(blank=True, max_length=254, null=True)),
            ],
        ),
    ]
