# Generated by Django 6.0.4 on 2026-04-13 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='personalacademico',
            options={'verbose_name': 'Personal Académico', 'verbose_name_plural': 'Personal Académico'},
        ),
    ]
