# Generated by Django 6.0.4 on 2026-04-25 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0002_alter_personalacademico_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='TutorNacional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_apellido', models.CharField(max_length=200)),
                ('programa_formacion', models.CharField(blank=True, max_length=255, null=True)),
                ('cedula', models.CharField(blank=True, max_length=20, null=True)),
                ('telefono', models.CharField(blank=True, max_length=50, null=True)),
                ('correo', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Tutor Nacional',
                'verbose_name_plural': 'Tutores Nacionales',
            },
        ),
        migrations.CreateModel(
            name='TutorRegional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cedula', models.CharField(max_length=20)),
                ('nombre_apellido', models.CharField(max_length=200)),
                ('entidad', models.CharField(max_length=100)),
                ('condicion_laboral', models.CharField(blank=True, max_length=50, null=True)),
                ('area_formacion', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Tutor Regional',
                'verbose_name_plural': 'Tutores Regionales',
            },
        ),
        migrations.RenameModel(
            old_name='PersonalAcademico',
            new_name='ResponsableAcademico',
        ),
        migrations.AlterModelOptions(
            name='responsableacademico',
            options={'verbose_name': 'Responsable Académico', 'verbose_name_plural': 'Responsables Académicos'},
        ),
    ]
